export const SEARCH_GROUPS='SEARCH_GROUPS';
export const SEARCH_GROUPS_START='SEARCH_GROUPS_START';
export const SEARCH_GROUPS_SUCCESS='SEARCH_GROUPS_SUCCESS';
export const SEARCH_GROUPS_FAILURE='SEARCH_GROUPS_FAILURE';


export const GET_GROUPS='GET_GROUPS';
export const GET_GROUPS_START='GET_GROUPS_START';
export const GET_GROUPS_SUCCESS='GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAILURE='GET_GROUPS_FAILURE';

export const GET_IMAGES_FOR_GROUP='GET_IMAGES_FOR_GROUP';
export const GET_IMAGES_FOR_GROUP_START='GET_IMAGES_FOR_GROUP_START';
export const GET_IMAGES_FOR_GROUP_SUCCESS='GET_IMAGES_FOR_GROUP_SUCCESS';
export const GET_IMAGES_FOR_GROUP_FAILURE='GET_IMAGES_FOR_GROUP_FAILURE';



export const SELECT_GROUP='SELECT_GROUP';